repos:
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort **/*.py
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: 'Doc Requirements'
        entry: poetry export --format=requirements.txt --without-hashes --dev --output=docs/requirements.txt
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: poetry run pylint --rcfile=.pylintrc src/apologies tests
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: poetry run mypy --config-file=.mypyrc src/apologies tests
        pass_filenames: false
        language: system
